import = ["/Users/franjs/.config/alacritty/colors.toml", "/Users/franjs/.config/alacritty/fonts.toml"]
live_config_reload = true

[bell]
animation = "Ease"
duration = 200

[colors]
draw_bold_text_with_bright_colors = true

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1~"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001B[4~"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
action = "None"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"
mode = "AppKeypad"

[[keyboard.bindings]]
chars = "\u001B[P"
key = "Delete"
mode = "~AppKeypad"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = """
:BufferLineCyclePrev
"""
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineCycleNext
"""
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 1
"""
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 2
"""
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 3
"""
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 4
"""
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 5
"""
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 6
"""
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 7
"""
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = """
:BufferLineGoToBuffer 8
"""
key = "Key8"
mods = "Command"

[window.dimensions]
columns = 180
lines = 55
