[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
# family = "Iosevka Nerd Font Mono"
# family = "Hack Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "Iosevka Nerd Font Mono"
# family = "Hack Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
# family = "Iosevka Nerd Font Mono"
# family = "Hack Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
# family = "Iosevka Nerd Font Mono"
# family = "Hack Nerd Font"

[font.offset]
x = 0
y = 0
